tools/tracing: Use tools/build makefiles on latency-collector
Use tools/build/ makefiles to build latency-collector, inheriting
the benefits of it. For example: Before this patch, a missing
tracefs/traceevents headers will result in fail like this:

-------------------------------- %< -------------------------------
~/linux/tools/tracing/latency $ make
cc -Wall -Wextra -g -O2  -o latency-collector latency-collector.c -lpthread
latency-collector.c:26:10: fatal error: tracefs.h: No such file or directory
   26 | #include <tracefs.h>
      |          ^~~~~~~~~~~
compilation terminated.
make: *** [Makefile:14: latency-collector] Error 1
-------------------------------- %< -------------------------------

Which is not that helpful. After this change it reports:

-------------------------------- %< -------------------------------
~/linux/tools/tracing/latency# make

Auto-detecting system features:
...                           libtraceevent: [ OFF ]
...                              libtracefs: [ OFF ]

libtraceevent is missing. Please install libtraceevent-dev/libtraceevent-devel
libtracefs is missing. Please install libtracefs-dev/libtracefs-devel
Makefile.config:29: *** Please, check the errors above..  Stop.
-------------------------------- %< -------------------------------

This type of output is common across other tools in tools/ like perf
and objtool.

Suggested-by: Linus Torvalds <torvalds@linux-foundation.org>
Signed-off-by: Daniel Bristot de Oliveira <bristot@kernel.org>